package com.pocketpass.app.mii

import kotlinx.serialization.Serializable

@Serializable
data class MiiAppearance(
    val schemaVersion: Int = CURRENT_SCHEMA_VERSION,
    val gender: Int = 0,
    val favoriteColor: Int = 0,
    val build: Int = 64,
    val height: Int = 64,
    val faceType: Int = 0,
    val skinColor: Int = 0,
    val wrinklesType: Int = 0,
    val makeupType: Int = 0,
    val hairType: Int = 33,
    val hairColor: Int = 1,
    val flipHair: Boolean = false,
    val eyeType: Int = 2,
    val eyeColor: Int = 0,
    val eyeScale: Int = 4,
    val eyeVerticalStretch: Int = 3,
    val eyeRotation: Int = 4,
    val eyeSpacing: Int = 2,
    val eyeYPosition: Int = 12,
    val eyebrowType: Int = 6,
    val eyebrowColor: Int = 1,
    val eyebrowScale: Int = 4,
    val eyebrowVerticalStretch: Int = 3,
    val eyebrowRotation: Int = 6,
    val eyebrowSpacing: Int = 2,
    val eyebrowYPosition: Int = 10,
    val noseType: Int = 1,
    val noseScale: Int = 4,
    val noseYPosition: Int = 9,
    val mouthType: Int = 23,
    val mouthColor: Int = 0,
    val mouthScale: Int = 4,
    val mouthHorizontalStretch: Int = 3,
    val mouthYPosition: Int = 13,
    val mustacheType: Int = 0,
    val mustacheScale: Int = 4,
    val mustacheYPosition: Int = 10,
    val beardType: Int = 0,
    val facialHairColor: Int = 0,
    val glassesType: Int = 0,
    val glassesColor: Int = 0,
    val glassesScale: Int = 4,
    val glassesYPosition: Int = 10,
    val moleEnabled: Boolean = false,
    val moleScale: Int = 4,
    val moleXPosition: Int = 2,
    val moleYPosition: Int = 20,
    val extHatType: Int = -1,
    val extHatColor: Int = -1,
    val extFacePaintColor: Int = -1,
    val extGlassesColor: Int = -1,
    val extHairColor: Int = -1,
    val extEyebrowColor: Int = -1,
    val extMouthColor: Int = -1,
    val extFacialHairColor: Int = -1,
) {
    fun normalized(): MiiAppearance = copy(
        schemaVersion = CURRENT_SCHEMA_VERSION,
        gender = gender.coerceIn(0, 1),
        favoriteColor = favoriteColor.coerceIn(0, 11),
        build = build.coerceIn(0, 127),
        height = height.coerceIn(0, 127),
        faceType = faceType.coerceIn(0, 11),
        skinColor = skinColor.coerceIn(0, 9),
        wrinklesType = wrinklesType.coerceIn(0, 11),
        makeupType = makeupType.coerceIn(0, 11),
        hairType = hairType.coerceIn(0, 131),
        hairColor = hairColor.coerceIn(0, 7),
        eyeType = eyeType.coerceIn(0, 59),
        eyeColor = eyeColor.coerceIn(0, 5),
        eyeScale = eyeScale.coerceIn(0, 7),
        eyeVerticalStretch = eyeVerticalStretch.coerceIn(0, 6),
        eyeRotation = eyeRotation.coerceIn(0, 7),
        eyeSpacing = eyeSpacing.coerceIn(0, 12),
        eyeYPosition = eyeYPosition.coerceIn(0, 18),
        eyebrowType = eyebrowType.coerceIn(0, 23),
        eyebrowColor = eyebrowColor.coerceIn(0, 7),
        eyebrowScale = eyebrowScale.coerceIn(0, 8),
        eyebrowVerticalStretch = eyebrowVerticalStretch.coerceIn(0, 6),
        eyebrowRotation = eyebrowRotation.coerceIn(0, 11),
        eyebrowSpacing = eyebrowSpacing.coerceIn(0, 12),
        eyebrowYPosition = eyebrowYPosition.coerceIn(3, 18),
        noseType = noseType.coerceIn(0, 17),
        noseScale = noseScale.coerceIn(0, 8),
        noseYPosition = noseYPosition.coerceIn(0, 18),
        mouthType = mouthType.coerceIn(0, 35),
        mouthColor = mouthColor.coerceIn(0, 4),
        mouthScale = mouthScale.coerceIn(0, 8),
        mouthHorizontalStretch = mouthHorizontalStretch.coerceIn(0, 6),
        mouthYPosition = mouthYPosition.coerceIn(0, 18),
        mustacheType = mustacheType.coerceIn(0, 5),
        mustacheScale = mustacheScale.coerceIn(0, 8),
        mustacheYPosition = mustacheYPosition.coerceIn(0, 16),
        beardType = beardType.coerceIn(0, 5),
        facialHairColor = facialHairColor.coerceIn(0, 7),
        glassesType = glassesType.coerceIn(0, 19),
        glassesColor = glassesColor.coerceIn(0, 5),
        glassesScale = glassesScale.coerceIn(0, 7),
        glassesYPosition = glassesYPosition.coerceIn(0, 20),
        moleScale = moleScale.coerceIn(0, 8),
        moleXPosition = moleXPosition.coerceIn(0, 16),
        moleYPosition = moleYPosition.coerceIn(0, 30),
        extHatType = extHatType.coerceIn(-1, 9),
        extHatColor = extHatColor.coerceIn(-1, 11),
        extFacePaintColor = extFacePaintColor.coerceIn(-1, 11),
        extGlassesColor = extGlassesColor.coerceIn(-1, 99),
        extHairColor = extHairColor.coerceIn(-1, 99),
        extEyebrowColor = extEyebrowColor.coerceIn(-1, 99),
        extMouthColor = extMouthColor.coerceIn(-1, 99),
        extFacialHairColor = extFacialHairColor.coerceIn(-1, 99),
    )

    companion object {
        const val CURRENT_SCHEMA_VERSION: Int = 1
    }
}
